title: My Awesome Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alpha7b.github.io/alpha" # Replace <username> and <repository>
twitter_username: your_twitter
github_username:  your_github

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
